app:
  name: CMAS
  port: 3000
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: cmas
  options: "sslmode=disable"
auth:
  jwt:
    secret: "7f8a9b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f"
